name: Deploy to GitHub Pages

on:
    push:
      branches:
        - v4
    workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0 # Fetch all history for git info
          - uses: actions/setup-node@v3
            with:
              node-version: 18.14
          - name: Install Dependencies
            run: npm ci
          - name: Build Quartz
            run: npx quartz build

          - uses: cpina/github-action-push-to-another-repository@main
            env:
                SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
            with:
                source-directory: "public"
                destination-github-username: "jpalczewski"
                destination-repository-name: "jpalczewski.github.io"
                user-email: actions@github.com
                target-branch: master
